version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install npx 

  build:
    commands:
      - echo "Building React project..."
      - npm run build 
      - cd build 
      - ls
      - pwd
      - aws s3 ls
  post_build:
    commands:
      - pwd
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync /build/pk/ s3://task-1-demo --delete  --debug

