version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install 

  build:
    commands:
      - echo "Building React project..."
      - npm run build 
      - cd build 
      - ls
      - pwd
  post_build:
    commands:
      - pwd
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync /codebuild/output/src543705156/src/github.com/pranaydhakate1/SnapShot/build/ s3://task-1-demo --delete  --debug

