version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npm audit fix --force
      - npm run build 
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --prod 
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/github-s3-task-demo/ s3://task-1-demo --delete
